### ISSUE TITLE
ClockIOT doesn't report local IP when timezone manually selected

### ISSUE THREAD

**Issue by ChaoticWyrme** [wyolum/ClockIOT#19]
When the timezone is manually selected, the clock doesn't request it's timezone from our server, and as such it never sends it's local IP to the server. This means that the browser UI can't find any clocks that are set to use a manual timezone. Currently, the only way to fix this problem after the previous local IP entry expires is to reset the clock or use the serial interface.

**Comment by wyojustin** [comment]
Ok, so now, as long as you have internet, arduino checks in with wyolum.com.  Only set timezone if "use ip timezone" is in effect.
