### ISSUE TITLE
Uploaded code does not work consistently

### ISSUE THREAD

**Issue by Anool** [wyolum/ClockIOT#2]
Issue affects Anool's CIOT.
[MFG_CODE](https://github.com/wyolum/ClockIOT/tree/master/arduino/ClockIOT_MFGTest) works fine.
Justin's pared down [BAREBONES CODE](https://github.com/wyolum/ClockIOT/tree/master/arduino/BareBones) works.

[ClockIoT CODE](https://github.com/wyolum/ClockIOT/tree/master/arduino/ClockIOT) does not work. Results are not consistent and non-reproducible.
ClockIoT code loads without error - always. 
AP mode works - most times. 
It picks up a local IP - some times. 
But there is no display on the LEDs - never (worked once for a few minutes).

**Comment by wyojustin** [comment]
I added ntp service to the bare bones code.  Can you pull and test again?

Barebones now uses wifi manager, so you may need to setup from the Klok hotspot as before.

**Comment by Anool** [comment]
WORKS.
