### ISSUE TITLE
Use tall buttons for mode Inc etc

### ISSUE THREAD

**Issue by wyojustin** [wyolum/ClockIOT#3]

**Comment by wyojustin** [comment]
Use low buttons for reset and boot

**Comment by Anool** [comment]
BoM updated.
Black Tall buttons for INC / DEC / MODE / ENTER
Red Short buttons for BOOT / EN
Updated BoM : https://github.com/wyolum/ClockIOT/blob/master/kicad/ClockIOT_BoM_seeed.xls
