### ISSUE TITLE
Run without internet

### ISSUE THREAD

**Issue by wyojustin** [wyolum/ClockIOT#4]
Right now, you need internet for the clock to run.  We need to be able to run in standalone mode.

**Comment by wyojustin** [comment]
Add "bool stand_alone" to the configuration setting and an interface to toggle it on start up.

**Comment by wyojustin** [comment]
Toggle use_wifi when Mode is depressed during start up.  Set time using buttons if use_wifi == false.

**Comment by Anool** [comment]
If I keep MODE pressed, and press RST, the Klok goes in to manual mode. I can set time (hours using Mode / Ent and Minutes using Inc / Dec). I think issue can be closed.
