### ISSUE TITLE
Power cord direction

### ISSUE THREAD

**Issue by Anool** [wyolum/ClockIOT#6]
In config.h
bool FLIP_DISPLAY = true; // true: cord out bottom, false: cord out top

If cord out bottom, we ought to flip all the text on the PCB by 180 deg.

Text laser engraved on rear acrylic cover will appear upside down (EN/INC/DEC/MODE). We can't change that and will probably have to live with it.

We ought to use a right angle micro-USB cord. Cable should point north when cord is plugged in to USB socket.

**Comment by Anool** [comment]
Like this

https://img.fasttechcdn.com/132/1329800/1329800-3.jpg

**Comment by wyojustin** [comment]
Thanks for opening this issue to facilitate this discussion.  I think the upside down back plate is no issue at all as long as we document it well in the instructions.  The cord lies perfectly, no right angle needed.

**Comment by Anool** [comment]
Sweet. Can you put the CIOT in an Ikea frame to see if the cord has any issues ?
If it works, this issue can be closed.

**Comment by wyojustin** [comment]
I'll test... doubt it cord fits in RIBBA frame.

**Comment by wyojustin** [comment]
I'll add a "flip_display" to the config file.

**Comment by wyojustin** [comment]
Added flip_display to the config file.  You can flip display in real time now.  I think we can close this issue.
