### ISSUE TITLE
USB connector anchoring

### ISSUE THREAD

**Issue by Anool** [wyolum/ClockIOT#9]
USB connector could likely get pulled out if cable is yanked.

Instructing SEEED to add extra solder on anchor tabs may help
OR
We can add two through hole pads next to the USB connector through which a piece of copper wire (component lead) can be soldered to retain the USB connector.

Adding the through holes is easy.
Deciding to add (or not) the extra retaining copper wire can be left for later.

**Comment by wyojustin** [comment]
While effective, the process sounds non-standard and manually intensive.  Extra solder should suffice.

**Comment by wyojustin** [comment]
Second unit broken.  USB felt secure, but came free after 3 weeks.

**Comment by Anool** [comment]
![2018-10-15](https://user-images.githubusercontent.com/760425/46946849-ad8a6480-d096-11e8-9141-f5cb1fd2f0ed.jpg)

**Comment by Anool** [comment]
Mandy from Seeed 
"We will optimize our production process in next batch, Modify the stencil and make sure there is enough tin for soldering. It will be solve the solder issue."

Anool will make changes to the Gerbers before submitting for Production.

**Comment by Anool** [comment]
Add row of header pins to allow USB-C breakout connection in future (also useful if UCB-micro connector gets ripped out)

https://www.pololu.com/blog/790/new-product-usb-2.0-type-c-connector-breakout-board

**Comment by Anool** [comment]
Moved some parts from around the USB-micro area to make space for the USB type-C breakout board from Pololu. Instead of using the Pololu breakout, it's also possible to just use the breakout pads to connect external 5V/D-/D+/GND. Details of Pololu breakout in this folder 
https://github.com/wyolum/ClockIOT/tree/master/kicad/ClockIOT_data/USB-C_breakout

There are no other major changes on the board other than some track re-routing.

![clockiot09](https://user-images.githubusercontent.com/760425/47228058-ee111780-d3e1-11e8-8914-4f93357c5da5.png)
